### ISSUE TITLE
[BUG REPORT] 学科・時間割の表記ゆれ

### ISSUE THREAD

**Issue by arumino-om** [kqnade/22sbot#7]
**・Error Information**
以下について、現在の釧路高専の制度との表記ゆれおよびミスが見受けられます。
- 学科表記
- `A-建築` の表記ミス
- 時間割の時間表記

**・Reproduce**
- 学科表記 & 建築の表記ミス: `/timetable` の学科サジェスチョンで確認可能
- 時間割の時間表記: `/timetable` 実行結果で確認可能

**・Expected behavior** 
現在の釧路高専の制度からみて、以下の表記が期待されます。
- 学科表記 → 分野表記
- 建築デザイン科 → 建築学分野
- `1限、2限…` → `1,2限、3,4限…`
  - 1限だけの講義や3限連続の講義もあるため、以上の表記を提案します

**・Screenshot**
None

**・Additional context** 
None

**Comment by kqnade** [comment]
公式サイトを基に表記を決定しようと思う
Issue内容の表記で行く予定
参照：https://www.kushiro-ct.ac.jp/sstudy/

**Comment by kqnade** [comment]
#14 の方で一部の表記を直します。

**Comment by kqnade** [comment]
対応完了！
